version: '3.7'

services:
  app:
    build:
      context: .
      args:
        APP_BASE_DIR: ${APP_BASE_DIR-.}
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    volumes:
      - ${APP_BASE_DIR-.}:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network
  web:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    ports:
      - 8181:80
    environment:
      # The Hostname for the FPM (needs to match the hostname for the `app`)
      PHP_FPM_HOST: app
    volumes:
      - ${APP_BASE_DIR-.}/public:/app/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network
  pgsql:
    image: postgres:14.7
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
      - POSTGRES_DB=${DB_DATABASE:-properties}
    ports:
      - "5433:5432"
    networks:
      - app-network
volumes:
  postgres_data:
    driver: local
networks:
  app-network:
    driver: bridge